Updated timer animation and functionality
sn163/Pomoparty pull request #6
Opened 2024-03-30 12:50 UTC by aleckslu

Timer radial animation now updates per second
Timer now works with hours

2024-03-30 21:30 UTC, sn163 requested changes

2024-03-30 21:30 UTC, sn163 commented on src/app/_components/Dashboard.tsx
> +	};
We need `clearInterval(timerRef.current)` here, toggling activeTimer won't clear the current interval in the useEffect

2024-03-30 23:45 UTC, aleckslu commented on src/app/_components/Dashboard.tsx
> +	const timeToSecs = (hr: number = 0, min: number, sec: number): number =>
accident, removed it

2024-03-31 04:36 UTC, sn163 approved these changes

2024-03-31 04:50 UTC, merged